node {
   stage('Clone') {
    git 'https://github.com/lunasouky/HelloWorld.git'
    }
    stage('Build') {
     sh '''javac src/main/java/HelloWorld.java'''
    }
    stage('Run') {
   sh 'java src/main/java/HelloWorld.java'
    }
}